#What config files will be copied each generation
tracked_files:
- /home/titleless/m2/Code/new/Python/fauxnix/src/test/idk/nefile.txt

#Only the 1000 most recent generations will be saved
history_length: 1000
#Pick date format. Default is dd/mm/yyyy
day_first: true

#The command to be run when reverting system
#Later include commented versions of other package managers
# update_command: "sudo pacman --needed -S - < "

#For aur support. Replace with yay if needed
update_command: 'paru --needed -S - < '

#TODO
#Currently assumes that pacman is available for deleting obsolete pkgs

#Required for when the script is run as root by pacman hook
uid: 1000
gid: 1000
