#What config files will be copied each generation
tracked_files: 
  - /home/titleless/.config/hypr/hyprland.conf
  - /home/titleless/.config/hypr/hyprpaper.conf

#Only the 1000 most recent generations will be saved
history_length: 1000

#The command to be run when reverting system
#Later include commented versions of other package managers
update_command: "sudo pacman -S - < "

